### ISSUE TITLE
Docker and Compose on Apple Silicon M1

### ISSUE THREAD

**Issue by johnpilbeam** [ezpaarse-project/ezpaarse#121]
Using Docker ([https://docs.docker.com/docker-for-mac/apple-silicon/](https://docs.docker.com/docker-for-mac/apple-silicon/)) on M1 MacBook Air _ezpaarse_db_ does not start. It is stuck in a 'RESTARTING' loop:

`runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x524da0, 0x9)
/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc820026000, 0xc820035fc0)
/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x555ce8, 0x0)
/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.main.func1()
/usr/local/go/src/runtime/proc.go:48 +0x2c
runtime.systemstack(0x5c4300)
/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
/usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820020770 sp=0xc820020768
runtime.main()
/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200207c0 sp=0xc820020770
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200207c8 sp=0xc8200207c0
...`

I know the image is intended for amd64 machines, but is there advice for M1 Macs? Thanks.

**Comment by dzoladz** [comment]
Have you attempted upgrading the database container to a Mongo version/image that supports ARM64 architectures?

In `docker-compose.yml`, change the image version tag to `6.0.2` and retry the `docker compose up -d` command.

```
  ezpaarse_db:
    container_name: ezpaarse_db
    image: mongo:6.0.2
    restart: unless-stopped
    ```
