### ISSUE TITLE
make update fails

### ISSUE THREAD

**Issue by jmcgranahan** [ezpaarse-project/ezpaarse#172]
EZPaarse will not start with the latest update on an Amazon Linux 2023 ARM server. It's giving the following error when trying to run "make update":

```
> ezpaarse@3.9.3 build
> nuxt build --no-generate

Nuxt 3.8.2 with Nitro 2.8.1                                         9:22:05 AM

 ERROR  Cannot read properties of undefined (reading 'options')     9:22:07 AM

  at axiosModule (node_modules/@nuxtjs/axios/lib/module.js:12:13)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:2439:101)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3702:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3789:5)
  at async Module.loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2584:19)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:73:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7)



 ERROR  Cannot read properties of undefined (reading 'options')     9:22:07 AM

make[1]: *** [Makefile:137: build-nuxt] Error 1
make[1]: Leaving directory '/apps/ezpaarse'
make: *** [Makefile:175: pull] Error 4

```

Tried running this command: `npm i -g nuxt`, but same result when re-running `make update`. Please advise.

**Comment by nojhamster** [comment]
Hi there, sorry for the late response ! This error seems to result from an incorrect version of `nuxt`. ezPAARSE depends on [Nuxt 2](https://github.com/ezpaarse-project/ezpaarse/blob/3.9.3/package.json#L54), but the `version 3` has been installed for some reason, and that causes `@nuxtjs/axios` to fail due to an incompatibility.

The command `npm i -g nuxt` may have installed the version `3` of Nuxt globally, however this version should not have an effect since ezPAARSE ships with its own version. Did you notice any error during the installation of ezPAARSE dependencies ? You can reinstall them with the command `make libs` (which is also part of `make` and `make update`).
